### ISSUE TITLE
ModApp v1 Roadmap

### ISSUE THREAD

**Issue by Aksem** [Aksem/modapp#4]
- [ ] :hourglass_flowing_sand:  migrate to pydantic v2 (#3 )
- [ ] migrate to google implementation of grpc instead of grpclib
- [ ] web transport: http server + websockets (#5)
- [ ] :hourglass_flowing_sand: Running tests in Github Actions (#3 )
- [ ] README
